### ISSUE TITLE
Earley Exception whith Epsilon Production

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#178]
Looks like this grammar:
N0 -> N0 N0, N0 -> epsilon

leads to this exceptions:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.github.samyadaleh.cltoolbox.common.TreeUtils.performLeftmostSubstitution(TreeUtils.java:108)
	at com.github.samyadaleh.cltoolbox.chartparsing.cfg.earley.CfgEarleyPredict.getConsequences(CfgEarleyPredict.java:54)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:280)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.doParse(Deduction.java:89)

**Comment by SamyaDaleh** [comment]
No, but I got an Exception with
G = <N, T, S, P>
N = {N0}
T = {t0, t1}
S = N0
P = {N0 -> t0, N0 -> t0 N0, N0 -> N0 N0, N0 -> N0, N0 -> ε}

**Comment by SamyaDaleh** [comment]
Or yes, I just accidentially wrote N= instead for the second rule.

**Comment by SamyaDaleh** [comment]
Funny, the exception refuses to occur in Debug mode.

**Comment by SamyaDaleh** [comment]
Fixed I guess, I just caught it.
