### ISSUE TITLE
Empty Input Is Handled Incorrectly

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#210]
```
2019-11-23T17:29:47.153MEZ	ERROR	com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController	http-listener-1(3)Name-http-listener-1(3)Id	Token  from input is not a terminal in the grammar.
java.text.ParseException: Token  from input is not a terminal in the grammar.
	at com.github.samyadaleh.cltoolbox.chartparsing.converter.GrammarToDeductionRulesConverter.convertToSchema(GrammarToDeductionRulesConverter.java:31) ~[CL-Toolbox.jar:?]
	at com.github.samyadaleh.cltoolbox.cli.Main.parseCfgFileAndConvertToSchema(Main.java:302) ~[CL-Toolbox.jar:?]
	at com.github.samyadaleh.cltoolbox.cli.Main.parseGrammarReaderAndConvertToParsingSchema(Main.java:153) ~[CL-Toolbox.jar:?]
	at com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController.returnParseTrace(DeductionRestController.java:57) ~[DeductionRestController.class:?]
```
Please fix.

**Comment by SamyaDaleh** [comment]
Fixed. Are you finally done with finding new bugs? ;)
