### ISSUE TITLE
Fix Exception

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#211]
```
grammar=N = {N0, N1, N2}
T = {t0, t1}
S = N2
P = {N2 -> ε, N0 -> ε, N2 -> N0 N1, N1 -> ε, N2 -> t0 t1, N1 -> ε}
&input=t0 t1&formalism=cfg&algorithm=cfg-topdown
```

causes an exception
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.github.samyadaleh.cltoolbox.common.parser.TokenReader.getNextToken(TokenReader.java:38)
	at com.github.samyadaleh.cltoolbox.common.parser.inner.InnerGrammarParser.invoke(InnerGrammarParser.java:31)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.<init>(Cfg.java:37)
	at com.github.samyadaleh.cltoolbox.common.parser.CfgParser.parseCfgReader(CfgParser.java:24)
	at com.github.samyadaleh.cltoolbox.cli.Main.parseCfgFileAndConvertToSchema(Main.java:289)
	at com.github.samyadaleh.cltoolbox.cli.Main.parseGrammarReaderAndConvertToParsingSchema(Main.java:153)
	at com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController.returnParseTrace(DeductionRestController.java:57)
```
Please fix.

**Comment by SamyaDaleh** [comment]
fixed
