### ISSUE TITLE
ArrayIndexOutOfBoundsException with CFG-CYK

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#212]
Please fix:
`[2019-12-07T19:13:34.625+0100] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=30 _ThreadName=http-listener-1(2)] [timeMillis: 1575742414625] [levelValue: 900] [[
  StandardWrapperValve[com.gitlab.samyadaleh.cltaskbox.rest.RestMain]: Servlet.service() for servlet com.gitlab.samyadaleh.cltaskbox.rest.RestMain threw exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.isInCanonicalTwoForm(Cfg.java:63)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.isInChomskyNormalForm(Cfg.java:83)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getCfgForCyk(GrammarToGrammarConverter.java:183)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToCfg(GrammarToGrammarConverter.java:29)
	at com.github.samyadaleh.cltoolbox.cli.Main.parseCfgFileAndConvertToSchema(Main.java:297)
	at com.github.samyadaleh.cltoolbox.cli.Main.parseGrammarReaderAndConvertToParsingSchema(Main.java:153)
	at com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController.returnParseTrace(DeductionRestController.java:57)`
with http://localhost:8080/cl_taskbox_war_exploded/rest/deduction?grammar=N%20%3D%20%7BN0%2C%20N1%2C%20N2%7D%0AT%20%3D%20%7Bt0%2C%20t1%7D%0AS%20%3D%20N1%0AP%20%3D%20%7BN1%20-%3E%20%CE%B5%2C%20N1%20-%3E%20t1%2C%20N1%20-%3E%20t0%20N2%2C%20N0%20-%3E%20t1%20N2%20t1%2C%20N2%20-%3E%20N0%2C%20N1%20-%3E%20%CE%B5%2C%20N1%20-%3E%20%CE%B5%2C%20N0%20-%3E%20N1%2C%20N1%20-%3E%20%CE%B5%2C%20N2%20-%3E%20t0%2C%20N2%20-%3E%20N0%7D%0A&input=t0%20t1&formalism=cfg&algorithm=cfg-cyk

**Comment by SamyaDaleh** [comment]
fixed
