### ISSUE TITLE
NPE in UselessSymbols

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#225]
Please fix:
```
[2019-12-26T09:01:04.684+0100] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=29 _ThreadName=http-listener-1(2)] [timeMillis: 1577347264684] [levelValue: 900] [[
  StandardWrapperValve[com.gitlab.samyadaleh.cltaskbox.rest.RestMain]: Servlet.service() for servlet com.gitlab.samyadaleh.cltaskbox.rest.RestMain threw exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.github.samyadaleh.cltoolbox.common.cfg.util.UselessSymbols.addEpsilonProductions(UselessSymbols.java:73)
	at com.github.samyadaleh.cltoolbox.common.cfg.util.UselessSymbols.getGeneratingSymbols(UselessSymbols.java:51)
	at com.github.samyadaleh.cltoolbox.common.cfg.util.UselessSymbols.removeNonGeneratingSymbols(UselessSymbols.java:17)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.getCfgWithoutNonGeneratingSymbols(Cfg.java:138)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getCfgForCyk(GrammarToGrammarConverter.java:186)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToCfg(GrammarToGrammarConverter.java:29)
	at com.gitlab.samyadaleh.cltaskbox.rest.TaskGeneratorRestController.returnInputAndGrammar(TaskGeneratorRestController.java:59)
```

**Comment by SamyaDaleh** [comment]
I consider this fixed until proven otherwise.
