### ISSUE TITLE
Exception in CfgProductionRule

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#226]
Please fix.
```
[2019-12-26T13:00:24.548+0100] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=30 _ThreadName=http-listener-1(3)] [timeMillis: 1577361624548] [levelValue: 900] [[
  StandardWrapperValve[com.gitlab.samyadaleh.cltaskbox.rest.RestMain]: Servlet.service() for servlet com.gitlab.samyadaleh.cltaskbox.rest.RestMain threw exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.github.samyadaleh.cltoolbox.common.cfg.CfgProductionRule.toString(CfgProductionRule.java:62)
	at com.github.samyadaleh.cltoolbox.common.cfg.util.LeftRecursion.removeLeftRecursion(LeftRecursion.java:105)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.getCfgWithoutLeftRecursion(Cfg.java:218)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getCfgForLeftCorner(GrammarToGrammarConverter.java:203)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToCfg(GrammarToGrammarConverter.java:27)
	at com.gitlab.samyadaleh.cltaskbox.rest.TaskGeneratorRestController.returnInputAndGrammar(TaskGeneratorRestController.java:59)
```

**Comment by SamyaDaleh** [comment]
I consider this fixed until proven otherwise.
