### ISSUE TITLE
NPE in SRCG Extended

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#233]
This is totally your fault:
```
java.lang.NullPointerException
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getSrcgForCykExtended(GrammarToGrammarConverter.java:251)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToSrcg(GrammarToGrammarConverter.java:101)
	at com.github.samyadaleh.cltoolbox.cli.Main.parseSrcgFileAndConvertToSchema(Main.java:203)
	at com.github.samyadaleh.cltoolbox.cli.Main.parseGrammarReaderAndConvertToParsingSchema(Main.java:172)
	at com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController.returnParseTrace(DeductionRestController.java:58)
```

Grammar:
```
G = <N, T, V, P, S>
N = {N0^1, N1^1, N11^1, S'}
T = {, t0, t1}
V = {X1, X2, X3}
P = {S'(ε) -> ε, S'(X1) -> N1^1(X1), N1^1(t0 X2) -> N11(X2), N1^1(t0 X1 X2) -> N1^1(X1) N11^1(X2), N11^1(X3) -> N1(X3), N11^1(X2) -> N1^1(X2), N11^1(X3) -> N1(X3), N11^1(X2 X3) -> N1^1(X2) N1^1(X3), N0^1(t1) -> ε, N1^1(t1 t0) -> ε, N1^1(X1) -> N0^1(X1)}
S = S'
```
w is the empty string.

**Comment by SamyaDaleh** [comment]
Also please note something went wrong in conversion, there is an empty terminal in it.

**Comment by SamyaDaleh** [comment]
Also the tree is wrong when parsing the empty string. Everything about this task is so broken!

**Comment by SamyaDaleh** [comment]
I think it was something like this before conversion:
```
T = t0, t1
N = {N0, N1}
P = {N1 -> t0 N1, N1 -> t0 N1 N1, N1 -> N1, N1 -> N1 N1, N0 -> t0, N1 -> t0 t1, N1 -> N0, N1 -> ε}
S = N1
```

**Comment by SamyaDaleh** [comment]
This is a bug NEST!

**Comment by SamyaDaleh** [comment]
I cannot reproduce the wrong conversion. Let's do it like this: in the backend create random grammars for that task until we get a Exception.

**Comment by SamyaDaleh** [comment]
Dis is terriblé.
So when
```
N = {N0, N1, N2, N3, N4, N5, N6}
T = {t0, t1, t2, t3, t4, t5, t6, t7}
S = N0
P = {N2 -> ε, N0 -> t0 t1 N1 N1, N1 -> ε}
```
is converted to a sRCG, in one conversion step fo src-cyk-extended the epsilon productions disappear and in the step that removes nonterminating symbols everything is removed and the srcg becomes null.

**Comment by SamyaDaleh** [comment]
```
N = {N0, N1}
T = {t0, t1, t2, t3}
S = N0
P = {N0 -> ε, N0 -> t0 t1, N1 -> ε}
```
```
java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.addNewStartSymbolAndHandleEmptyWord(EmptyProductions.java:109)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getSrcgWithoutEmptyProductions(EmptyProductions.java:52)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.Srcg.getSrcgWithoutEmptyProductions(Srcg.java:314)
```

**Comment by SamyaDaleh** [comment]
```
Grammar generated: G = <N, T, S, P>
N = {N0, N1, N2}
T = {t0, t1}
S = N1
P = {N1 -> t0 t1, N2 -> t1 N0, N1 -> ε, N2 -> N0, N2 -> t0 N0 N0 N1 t1}
```
```
java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getClauseForEpsilonCombination(EmptyProductions.java:137)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getSrcgWithoutEmptyProductions(EmptyProductions.java:57)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.Srcg.getSrcgWithoutEmptyProductions(Srcg.java:314)
```
I'm bugfixing the shit out of it!!

**Comment by SamyaDaleh** [comment]
```
Grammar generated: G = <N, T, S, P>
N = {N0, N1, N2, N3}
T = {t0, t1}
S = N2
P = {N2 -> t0 N3 t1, N1 -> t0 N3, N0 -> ε, N2 -> ε, N3 -> t1, N2 -> ε, N3 -> ε}
```


```
java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getClauseForEpsilonCombination(EmptyProductions.java:142)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getSrcgWithoutEmptyProductions(EmptyProductions.java:61)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.Srcg.getSrcgWithoutEmptyProductions(Srcg.java:315)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getSrcgForCykGeneral(GrammarToGrammarConverter.java:270)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToSrcg(GrammarToGrammarConverter.java:103)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToSrcg(GrammarToGrammarConverter.java:119)
```

**Comment by SamyaDaleh** [comment]
Call with algorithm: srcg-cyk-extended

Grammar after conversion for task: ```
G = <N, T, V, P, S>
N = {S'}
T = {}
V = {}
P = {S'(ε) -> ε}
S = S'
```

Looks like it hangs.

**Comment by SamyaDaleh** [comment]
I detroyed the whole bug nest, looks good now.

**Comment by SamyaDaleh** [comment]
The original bug is still open.

**Comment by SamyaDaleh** [comment]
I mean, the error message occurs, because the conversion was wrong, thus shouldn't occur anymore by chance. Nevertheless a more clear error message should be returned.

**Comment by SamyaDaleh** [comment]
Should've read the threat to the end ... the original grammar is wrong, it contains N3 which is not declared as nonterminal. Cannot reproduce any NPE anymore.

**Comment by SamyaDaleh** [comment]
Original bug is still there. CL Taskbox receives an unspecified error instead of a note about the wrong symbol.

**Comment by SamyaDaleh** [comment]
Finally nailed down and fixed.
