### ISSUE TITLE
ArrayIndexOutOfBoundsException in Left Recursion Removal

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#237]
```
Grammar generated: G = <N, T, S, P>
N = {N0, N1, N2, N3, N4, N5}
T = {t0, t1, t2, t3, t4, t5, t6, t7, t8}
S = N0
P = {N2 -> N1 N3 t0 t1, N3 -> ε, N0 -> ε, N1 -> ε, N2 -> ε, N0 -> ε, N1 -> t1, N0 -> N2, N0 -> ε}




java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.samyadaleh.cltoolbox.common.cfg.util.LeftRecursion.nonterminalIsLhsOfLeftRecursion(LeftRecursion.java:174)
	at com.github.samyadaleh.cltoolbox.common.cfg.util.LeftRecursion.removeLeftRecursion(LeftRecursion.java:109)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.getCfgWithoutLeftRecursion(Cfg.java:218)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getCfgForLeftCorner(GrammarToGrammarConverter.java:203)
```

**Comment by SamyaDaleh** [comment]
Cannot reproduce.
