### ISSUE TITLE
LCFRS CYK Vector Ranges Match Fail

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#238]
```
Grammar after conversion: G = <N, T, V, P, S>
N = {N0^1, N01^1, S'}
T = {t1, t0}
V = {X1, X3, X2}
P = {S'(ε) -> ε, S'(X1) -> N0^1(X1), N0^1(t1 t0) -> ε, N0^1(t1 t0 X1) -> N0^1(X1), N0^1(t0 X1 t1) -> N01^1(X1), N0^1(t0 X1 t1 X3) -> N0^1(X3) N01^1(X1), N01^1(X1) -> N0^1(X1), N01^1(X2) -> N0^1(X2), N01^1(X1 X2) -> N0^1(X1) N0^1(X2)}
S = S'

generated: [N01^1, (<1,3>)] with trees: (N01^1 (N0^1 (t1<1> )(t0<2> ))), from: [N0^1, (<1,3>)] with rule complete-unary N01^1(X2) -> N0^1(X2)
generated: [N01^1, (<1,3>)] with trees: (N01^1 (N0^1 (t1<1> )(t0<2> ))), from: [N0^1, (<1,3>)] with rule complete-unary N01^1(X1) -> N0^1(X1)
generated: [S', (<1,3>)] with trees: (S' (N0^1 (t1<1> )(t0<2> ))), from: [N0^1, (<1,3>)] with rule complete-unary S'(X1) -> N0^1(X1)
generated: [N01^1, (<4,6>)] with trees: (N01^1 (N0^1 (t1<4> )(t0<5> ))), from: [N0^1, (<4,6>)] with rule complete N01^1(X2) -> N0^1(X2)
generated: [N01^1, (<4,6>)] with trees: (N01^1 (N0^1 (t1<4> )(t0<5> ))), from: [N0^1, (<4,6>)] with rule complete N01^1(X1) -> N0^1(X1)
generated: [S', (<4,6>)] with trees: (S' (N0^1 (t1<4> )(t0<5> ))), from: [N0^1, (<4,6>)] with rule complete S'(X1) -> N0^1(X1)



java.lang.ArrayIndexOutOfBoundsException: -2

	at com.github.samyadaleh.cltoolbox.chartparsing.lcfrs.cyk.SrcgCykBinary.isVectorRangesMatch(SrcgCykBinary.java:70)
	at com.github.samyadaleh.cltoolbox.chartparsing.lcfrs.cyk.SrcgCykBinary.calculateConsequences(SrcgCykBinary.java:41)
	at com.github.samyadaleh.cltoolbox.chartparsing.dynamicdeductionrule.AbstractDynamicDecutionRuleTwoAntecedences.getConsequences(AbstractDynamicDecutionRuleTwoAntecedences.java:15)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:333)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:325)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.doParse(Deduction.java:126)
```

**Comment by SamyaDaleh** [comment]
Now I have to guess the input string?? Please provide more detailed bug reports in the future.

**Comment by SamyaDaleh** [comment]
fixed
