### ISSUE TITLE
ArrayIndexOutOfBoundsException on Binarization

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#240]
```
Grammar generated: G = <N, T, S, P>
N = {N0, N1, N2, N3, N4, N5, N6}
T = {t0, t1, t2, t3, t4, t5, t6, t7, t8}
S = N2
P = {N0 -> t1, N0 -> t0 N0, N2 -> N0, N0 -> ε}




java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.samyadaleh.cltoolbox.common.cfg.util.Binarization.doBinarize(Binarization.java:61)
	at com.github.samyadaleh.cltoolbox.common.cfg.util.Binarization.binarize(Binarization.java:20)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.getBinarizedCfg(Cfg.java:123)
```

**Comment by SamyaDaleh** [comment]
Cannot reproduce. Please report with more detailed logs next time.
