### ISSUE TITLE
StringIndexOutOfBoundsException in TreeUtils from CfgBottomUpReduce

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#242]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_212-8u]
	at com.github.samyadaleh.cltoolbox.common.TreeUtils.performLeftmostSubstitution(TreeUtils.java:108) ~[CL-Toolbox.jar:?]
	at com.github.samyadaleh.cltoolbox.chartparsing.cfg.shiftreduce.CfgBottomUpReduce.getConsequences(CfgBottomUpReduce.java:56) [CL-Toolbox.jar:?]
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:333) [CL-Toolbox.jar:?]
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:325) [CL-Toolbox.jar:?]
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.doParse(Deduction.java:126) [CL-Toolbox.jar:?]

[cltaskbox-test.log](https://github.com/SamyaDaleh/CL-Toolbox/files/4360059/cltaskbox-test.log)

**Comment by SamyaDaleh** [comment]
This is on purpose and logged on debug level. The parsing stopped because of those 1000 lines limit.
