### ISSUE TITLE
ArrayIndexOutOfBoundsException in Predicate.java:127

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#243]
Grammar generated: G = <N, T, S, P>
N = {N0}
T = {t0, t1}
S = N0
P = {N0 -> ε, N0 -> t0 N0 N0 N0 N0 t1}

Doing nothing with predicate N0(X1)
Doing nothing with predicate N0(X2)
Doing nothing with predicate N0(X3)
Doing nothing with predicate N0(X4)
Doing nothing with predicate N0(X1)
Doing nothing with predicate N0(X2)
Doing nothing with predicate N01(X1,X3)
Doing nothing with predicate N0(X3)
Doing nothing with predicate N0(X4)

java.lang.ArrayIndexOutOfBoundsException: 1

	at com.github.samyadaleh.cltoolbox.common.lcfrs.Predicate.getArgumentByIndex(Predicate.java:127)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getClauseForEpsilonCombination(EmptyProductions.java:157)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.util.EmptyProductions.getSrcgWithoutEmptyProductions(EmptyProductions.java:61)
	at com.github.samyadaleh.cltoolbox.common.lcfrs.Srcg.getSrcgWithoutEmptyProductions(Srcg.java:315)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getSrcgForCykExtended(GrammarToGrammarConverter.java:254)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToSrcg(GrammarToGrammarConverter.java:101)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToSrcg(GrammarToGrammarConverter.java:119)
	at com.gitlab.samyadaleh.cltaskbox.rest.TaskGeneratorRestController.returnInputAndGrammar(TaskGeneratorRestController.java:56)
	at com.gitlab.samyadaleh.cltaskbox.RandomBugSearcherTest.testTryToProvokeException(RandomBugSearcherTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by SamyaDaleh** [comment]
Something fails in getSrcgWithoutEmptyProductions before that. Suddenly there is a Nonterminal N01, that could be wrong.

**Comment by SamyaDaleh** [comment]
Nonsense, it already arrives with N01.

**Comment by SamyaDaleh** [comment]
before Binarization:
```
G = <N, T, V, P, S>
N = {N0}
T = {t0, t1}
V = {X1, X2, X3, X4}
P = {N0(ε) -> ε, N0(t0 X1 X2 X3 X4 t1) -> N0(X1) N0(X2) N0(X3) N0(X4)}
S = N0
```


after:
```
G = <N, T, V, P, S>
N = {N0, N01, N02}
T = {t0, t1}
V = {X1, X2, X3, X4}
P = {N0(ε) -> ε, N0(t0 X1 X2 t1) -> N0(X1) N01(X2), N0(t0 X1 X2 X3 t1) -> N0(X2) N02(X1,X3), N02(X1,X3 X4) -> N0(X3) N0(X4)}
S = N0
```
This is wrong. N01 must appear as lhs.

**Comment by SamyaDaleh** [comment]
The one above is fixed.
Now I end up with an empty grammar. Maybe in empty removal the one where it ends with only t0 t1 got missing, it's hard to see.
before empty removal:

```
G = <N, T, V, P, S>
N = {N0, N01, N02}
T = {t0, t1}
V = {X1, X2, X3, X4}
P = {N0(ε) -> ε, N0(t0 X1 X2 t1) -> N0(X1) N01(X2), N01(X2 X3) -> N0(X2) N02(X3), N02(X3 X4) -> N0(X3) N0(X4)}
S = N0
```


after:
```
G = <N, T, V, P, S>
N = {N0^1, N01^1, N02^1, S'}
T = {t0, t1}
V = {X1, X2, X3, X4}
P = {S'(ε) -> ε, S'(X1) -> N0^1(X1), N0^1(t0 X2 t1) -> N01^1(X2), N0^1(t0 X1 X2 t1) -> N0^1(X1) N01^1(X2), N01^1(X3) -> N02^1(X3), N01^1(X2 X3) -> N0^1(X2) N02^1(X3), N02^1(X3) -> N0^1(X3), N02^1(X4) -> N0^1(X4), N02^1(X3 X4) -> N0^1(X3) N0^1(X4)}
S = S'

```

**Comment by SamyaDaleh** [comment]
fixed
