### ISSUE TITLE
ArrayIndexOutOfBoundsException in CFG Binarizaion 61

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#247]
Grammar generated: G = <N, T, S, P>
N = {N0, N1, N2, N3}
T = {t0, t1}
S = N3
P = {N3 -> N0, N2 -> N0, N2 -> ε, N0 -> t1, N0 -> ε, N2 -> t1, N2 -> ε, N0 -> t0 t1 N2}

```
java.lang.ArrayIndexOutOfBoundsException: 0

	at com.github.samyadaleh.cltoolbox.common.cfg.util.Binarization.doBinarize(Binarization.java:61)
	at com.github.samyadaleh.cltoolbox.common.cfg.util.Binarization.binarize(Binarization.java:20)
	at com.github.samyadaleh.cltoolbox.common.cfg.Cfg.getBinarizedCfg(Cfg.java:123)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.getCfgForCykExtended(GrammarToGrammarConverter.java:170)
	at com.github.samyadaleh.cltoolbox.cli.GrammarToGrammarConverter.checkAndMayConvertToCfg(GrammarToGrammarConverter.java:31)
	
```

**Comment by SamyaDaleh** [comment]
Doesn't happen for me. Was this already fixed?
