### ISSUE TITLE
StringIndexOutOfBoundsException in TreeUtils from SrcgCykBinary

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#248]
Grammar read from file: G = <N, T, V, P, S>
N = {N0^1, N01^1, S'}
T = {t2, t1, t0}
V = {X1, X2, X3}
P = {S'(ε) -> ε, S'(X1) -> N0^1(X1), N0^1(t2 t1 X2) -> N01^1(X2), N0^1(t2 X1 t1 X2) -> N0^1(X1) N01^1(X2), N01^1(X2) -> N0^1(X2), N01^1(X3) -> N0^1(X3), N01^1(X2 X3) -> N0^1(X2) N0^1(X3), N0^1(t0 t2) -> ε, N0^1(t0 t2 X1) -> N0^1(X1), N0^1(t0 t2 X2) -> N0^1(X2), N0^1(t0 t2 X1 X2) -> N0^1(X1) N0^1(X2), N0^1(t2) -> ε, N0^1(t0 t1) -> ε}
S = S'

Grammar after conversion: G = <N, T, V, P, S>
N = {N0^1, N01^1, S'}
T = {t2, t1, t0}
V = {X1, X2, X3}
P = {S'(ε) -> ε, S'(X1) -> N0^1(X1), N0^1(t2 t1 X2) -> N01^1(X2), N0^1(t2 X1 t1 X2) -> N0^1(X1) N01^1(X2), N01^1(X2) -> N0^1(X2), N01^1(X3) -> N0^1(X3), N01^1(X2 X3) -> N0^1(X2) N0^1(X3), N0^1(t0 t2) -> ε, N0^1(t0 t2 X1) -> N0^1(X1), N0^1(t0 t2 X2) -> N0^1(X2), N0^1(t0 t2 X1 X2) -> N0^1(X1) N0^1(X2), N0^1(t2) -> ε, N0^1(t0 t1) -> ε}
S = S'

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

	at java.lang.String.substring(String.java:1967)
	at com.github.samyadaleh.cltoolbox.common.TreeUtils.performLeftmostSubstitution(TreeUtils.java:108)
	at com.github.samyadaleh.cltoolbox.chartparsing.lcfrs.cyk.SrcgCykBinary.calculateDerivatedTrees(SrcgCykBinary.java:107)
	at com.github.samyadaleh.cltoolbox.chartparsing.lcfrs.cyk.SrcgCykBinary.calculateConsequences(SrcgCykBinary.java:49)
	at com.github.samyadaleh.cltoolbox.chartparsing.dynamicdeductionrule.AbstractDynamicDecutionRuleTwoAntecedences.getConsequences(AbstractDynamicDecutionRuleTwoAntecedences.java:15)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:333)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:325)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.doParse(Deduction.java:126)
	at com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController.returnParseTrace(DeductionRestController.java:61)
	at com.gitlab.samyadaleh.cltaskbox.RandomBugSearcherTest.testTryToProvokeException(RandomBugSearcherTest.java:60)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


```

**Comment by SamyaDaleh** [comment]
Cannot reproduce. Please provide input string next time.
