### ISSUE TITLE
ArrayOutOfBoundsException in Predicate 120

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#252]
Call with algorithm: srcg-earley
Grammar after conversion for task: G = <N, T, V, P, S>
N = {N0^[1]^1, S'}
T = {t0, t1}
V = {X1, X2}
P = {S'(ε) -> ε, S'(X1) -> N0^[1]^1(X1), N0^[1]^1(t0) -> ε, N0^[1]^1(t0 t1) -> ε, N0^[1]^1(t0 X1 t1) -> N0^[1]^1(X1), N0^[1]^1(t0 X2 t1) -> N0^[1]^1(X2), N0^[1]^1(t0 X1 X2 t1) -> N0^[1]^1(X1) N0^[1]^1(X2)}
S = S'

Random Input generated: t0 t0 t0 t0 t1 t1

java.lang.ArrayIndexOutOfBoundsException: 1

	at com.github.samyadaleh.cltoolbox.common.lcfrs.Predicate.getSymAt(Predicate.java:120)
	at com.github.samyadaleh.cltoolbox.chartparsing.lcfrs.earley.SrcgEarleyComplete.calculateConsequences(SrcgEarleyComplete.java:58)
	at com.github.samyadaleh.cltoolbox.chartparsing.dynamicdeductionrule.AbstractDynamicDecutionRuleTwoAntecedences.getConsequences(AbstractDynamicDecutionRuleTwoAntecedences.java:14)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:333)

**Comment by SamyaDaleh** [comment]
[cl.log](https://github.com/SamyaDaleh/CL-Toolbox/files/4480178/cl.log)

**Comment by SamyaDaleh** [comment]
fixed
