### ISSUE TITLE
StringIndexOutOfBoundsException when cfg-leftcorner-chart parses empty word

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#253]
```
[2020-04-15T20:06:50.812+0200] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=28 _ThreadName=http-listener-1(3)] [timeMillis: 1586974010812] [levelValue: 900] [[
  StandardWrapperValve[com.gitlab.samyadaleh.cltaskbox.rest.RestMain]: Servlet.service() for servlet com.gitlab.samyadaleh.cltaskbox.rest.RestMain threw exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.github.samyadaleh.cltoolbox.common.TreeUtils.performLeftmostSubstitution(TreeUtils.java:108)
	at com.github.samyadaleh.cltoolbox.chartparsing.cfg.leftcorner.chart.CfgLeftCornerChartRemove.handleDotBeforeLastSymbol(CfgLeftCornerChartRemove.java:94)
	at com.github.samyadaleh.cltoolbox.chartparsing.cfg.leftcorner.chart.CfgLeftCornerChartRemove.calculateConsequences(CfgLeftCornerChartRemove.java:43)
	at com.github.samyadaleh.cltoolbox.chartparsing.dynamicdeductionrule.AbstractDynamicDecutionRuleTwoAntecedences.getConsequences(AbstractDynamicDecutionRuleTwoAntecedences.java:15)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:333)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:474)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.triggerTreeUpdate(Deduction.java:451)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.processNewItems(Deduction.java:425)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:335)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:474)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.triggerTreeUpdate(Deduction.java:451)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.processNewItems(Deduction.java:425)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:335)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:325)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.doParse(Deduction.java:126)
```
When parsing the empty string with
```
G = <N, T, S, P>
N = {S}
T = {}
S = S
P = {S -> S S, S -> ε}
```

**Comment by SamyaDaleh** [comment]
fixed
