### ISSUE TITLE
Grammar with Subscripts causes Tree Errors

### ISSUE THREAD

**Issue by SamyaDaleh** [SamyaDaleh/CL-Toolbox#269]
```
G = <N, T, S, P>
N = {S, q_0}
T = {a, b}
S = q_0
P = {S -> S a, S -> S b, q_0 -> S a, q_0 -> S b, S -> ε}
```
`w = a b`

causes

```
[2020-10-11T10:30:08.021+0200] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=28 _ThreadName=http-listener-1(1)] [timeMillis: 1602405008021] [levelValue: 900] [[
  StandardWrapperValve[com.gitlab.samyadaleh.cltaskbox.rest.RestMain]: Servlet.service() for servlet com.gitlab.samyadaleh.cltaskbox.rest.RestMain threw exception
java.text.ParseException: Unknown subscript 0
	at com.github.samyadaleh.cltoolbox.common.tag.Tree.handleSubscript(Tree.java:88)
	at com.github.samyadaleh.cltoolbox.common.tag.Tree.<init>(Tree.java:63)
	at com.github.samyadaleh.cltoolbox.common.tag.Tree.<init>(Tree.java:147)
	at com.github.samyadaleh.cltoolbox.chartparsing.cfg.leftcorner.CfgLeftCornerUtils.generateDerivedChartTrees(CfgLeftCornerUtils.java:23)
	at com.github.samyadaleh.cltoolbox.chartparsing.cfg.leftcorner.chart.CfgLeftCornerChartReduce.getConsequences(CfgLeftCornerChartReduce.java:35)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:343)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.applyRule(Deduction.java:335)
	at com.github.samyadaleh.cltoolbox.chartparsing.Deduction.doParse(Deduction.java:136)
	at com.gitlab.samyadaleh.cltaskbox.rest.DeductionRestController.returnParseTrace(DeductionRestController.java:61)
```

**Comment by SamyaDaleh** [comment]
That symbol does not occur ususually in any natural or artificial grammar. It should return a parse exception and I should make sure that the conversion to left-linear grammars does not produce any.

**Comment by SamyaDaleh** [comment]
done
